max_frames: 32
resolution:
- 512
- 768
round: 1
ddim_timesteps: 30
seed: 12345
save_fps: 8.0
test_list_path:
- - 1
  - C:/Users/Tsvetochek/app_pages/move/data/images/test.jpeg
  - C:/Users/Tsvetochek/app_pages/move/data/save_posed
  - C:/Users/Tsvetochek/app_pages/move/data/saved_frames
  - C:/Users/Tsvetochek/app_pages/move/data/saved_pkl/dance1_right.pkl
  - 12345
log_dir: results
test_model: C:/Users/Tsvetochek/app_pages/move/checkpoints/animate-x_ckpt.pth
partial_keys:
- - image
  - local_image
  - dwpose
  - pose_embeddings
TASK_TYPE: inference_animate_x_entrance
use_fp16: true
guide_scale: 2.5
vit_resolution:
- 224
- 224
batch_size: 1
latent_random_ref: true
chunk_size: 2
decoder_bs: 2
scale: 8
use_fps_condition: false
embedder:
  type: FrozenOpenCLIPTextVisualEmbedder
  layer: penultimate
  pretrained: C:/Users/Tsvetochek/app_pages/move/checkpoints/open_clip_pytorch_model.bin
auto_encoder:
  type: AutoencoderKL
  ddconfig:
    double_z: true
    z_channels: 4
    resolution: 256
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult:
    - 1
    - 2
    - 4
    - 4
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    video_kernel_size:
    - 3
    - 1
    - 1
  embed_dim: 4
  pretrained: C:/Users/Tsvetochek/app_pages/move/checkpoints/v2-1_512-ema-pruned.ckpt
UNet:
  type: UNetSD_Animate_X
  config: null
  in_dim: 4
  num: 0
  no_hand: true
  dim: 320
  y_dim: 1024
  context_dim: 1024
  out_dim: 4
  dim_mult:
  - 1
  - 2
  - 4
  - 4
  num_heads: 8
  head_dim: 64
  num_res_blocks: 2
  dropout: 0.1
  temporal_attention: true
  num_tokens: 4
  temporal_attn_times: 1
  use_checkpoint: true
  use_fps_condition: false
  use_sim_mask: false
  seq_len: 33
video_compositions:
- image
- local_image
- dwpose
- randomref
- randomref_pose
- pose_embedding
Diffusion:
  type: DiffusionDDIM
  schedule: linear_sd
  schedule_param:
    num_timesteps: 1000
    init_beta: 0.00085
    last_beta: 0.012
    zero_terminal_snr: true
  mean_type: v
  loss_type: mse
  var_type: fixed_small
  rescale_timesteps: false
  noise_strength: 0.1
use_DiffusionDPM: false
CPU_CLIP_VAE: true
